DROP TABLE Innings;
DROP TABLE GameUmpires;
DROP TABLE Games;
DROP TABLE Umpires;
DROP TABLE TeamPlayers;
DROP TABLE Teams;
DROP TABLE Players;
CREATE TABLE Players (
	PlayerID		INTEGER PRIMARY KEY,
	Name			TEXT			NOT NULL
);
CREATE TABLE Teams (
	TeamID			INTEGER PRIMARY KEY,
	TeamName		TEXT			NOT NULL
);
CREATE TABLE TeamPlayers (
	PlayerID		INT,
	TeamID			INT,
	CONSTRAINT		TeamPlayersPK		PRIMARY KEY (PlayerID, TeamID),
	CONSTRAINT		PlayerIDFK			FOREIGN KEY (PlayerID)		REFERENCES Players(PlayerID),
	CONSTRAINT		TeamIDFK			FOREIGN KEY (TeamID)		REFERENCES Teams(TeamID)
);
CREATE TABLE Umpires (
	UmpireID		INTEGER PRIMARY KEY,
	Name			TEXT			NOT NULL
);
CREATE TABLE Games (
	GameID			INTEGER PRIMARY KEY,
	HomeID			INT,
	AwayID			INT,
	GameDate		DATE				NOT NULL,
	TossResult		TEXT			NOT NULL,
	Decision		TEXT			NOT NULL,
	MatchType		TEXT			NOT NULL,
	OversOrDays		INT					NOT NULL,
	CONSTRAINT		HomeFK				FOREIGN KEY (HomeID)		REFERENCES Teams(TeamID),
	CONSTRAINT		AwayFK				FOREIGN KEY (AwayID)		REFERENCES Teams(TeamID)
);
CREATE TABLE GameUmpires (
	GameID			INT,
	UmpiresID		INT,
	CONSTRAINT		GameUmpirePK		PRIMARY KEY (GameID, UmpiresID),
	CONSTRAINT		GameUmpiresGameID	FOREIGN KEY (GameID)		REFERENCES Games(GameID),
	CONSTRAINT		GameUmpiresID		FOREIGN KEY (UmpiresID)		REFERENCES Umpires(UmpireID)
);
CREATE TABLE Innings (
	GameID			INT,
	BattingTeamID	INT,
	InningNumber	INT,
	FallOfWickets	TEXT,
	Score			TEXT,
	CONSTRAINT		InningsPK			PRIMARY KEY (GameID, BattingTeamID, InningNumber),
	CONSTRAINT		InningsGameFK		FOREIGN KEY (GameID)		REFERENCES Games(GameID),
	CONSTRAINT		InningsTeamFK		FOREIGN KEY (BattingTeamID)	REFERENCES Teams(TeamID)
);

DROP TABLE Innings;
DROP TABLE GameUmpires;
DROP TABLE Games;
DROP TABLE Umpires;
DROP TABLE TeamPlayers;
DROP TABLE Teams;
DROP TABLE Players;
CREATE TABLE Players (PlayerID INTEGER PRIMARY KEY AUTOINCREMENT, Name TEXT NOT NULL);
CREATE TABLE Teams (TeamID INTEGER PRIMARY KEY AUTOINCREMENT, TeamName TEXT NOT NULL);
CREATE TABLE TeamPlayers (PlayerID INT, TeamID INT, CONSTRAINT TeamPlayersPK PRIMARY KEY (PlayerID, TeamID), CONSTRAINT PlayerIDFK FOREIGN KEY (PlayerID) REFERENCES Players(PlayerID), CONSTRAINT TeamIDFK FOREIGN KEY (TeamID) REFERENCES Teams(TeamID));
CREATE TABLE Umpires (UmpireID INTEGER PRIMARY KEY AUTOINCREMENT, Name TEXT NOT NULL);
CREATE TABLE Games (GameID INTEGER PRIMARY KEY AUTOINCREMENT, HomeID INT, AwayID INT, GameDate DATE NOT NULL, TossResult TEXT NOT NULL, Decision TEXT NOT NULL, MatchType TEXT NOT NULL, OversOrDays INT NOT NULL, CONSTRAINT HomeFK FOREIGN KEY (HomeID) REFERENCES Teams(TeamID), CONSTRAINT AwayFK FOREIGN KEY (AwayID) REFERENCES Teams(TeamID));
CREATE TABLE GameUmpires (GameID INT, UmpiresID INT, CONSTRAINT GameUmpirePK PRIMARY KEY (GameID, UmpiresID), CONSTRAINT GameUmpiresGameID FOREIGN KEY (GameID) REFERENCES Games(GameID), CONSTRAINT GameUmpiresID FOREIGN KEY (UmpiresID) REFERENCES Umpires(UmpireID));
CREATE TABLE Innings (GameID INT, BattingTeamID INT, InningNumber INT, FallOfWickets TEXT, Score TEXT, CONSTRAINT InningsPK PRIMARY KEY (GameID, BattingTeamID, InningNumber), CONSTRAINT InningsGameFK FOREIGN KEY (GameID) REFERENCES Games(GameID), CONSTRAINT InningsTeamFK FOREIGN KEY (BattingTeamID) REFERENCES Teams(TeamID));


