DROP TABLE Innings;
DROP TABLE Games;
DROP TABLE Players;
DROP TABLE Teams;
CREATE TABLE Teams (
	TeamID			INTEGER PRIMARY KEY AUTOINCREMENT,
	TeamName		TEXT			NOT NULL
);
CREATE TABLE Players (
	TeamID			INT,
	PlayerName		TEXT,
	CONSTRAINT		PlayersPK			PRIMARY KEY (TeamID, PlayerName),
	CONSTRAINT		PlayersFK			FOREIGN KEY (TeamID)		REFERENCES Teams(TeamID)
);
CREATE TABLE Games (
	GameID			INTEGER PRIMARY KEY AUTOINCREMENT,
	HomeID			INT,
	AwayID			INT,
	GameDate		DATE				NOT NULL,
	TossResult		TEXT				NOT NULL,
	Decision		TEXT				NOT NULL,
	MatchType		TEXT				NOT NULL,
	OversOrDays		INT					NOT NULL,
	UmpireOne		TEXT				NOT NULL,
	UmpireTwo		TEXT				NOT NULL,
	CONSTRAINT		HomeFK				FOREIGN KEY (HomeID)		REFERENCES Teams(TeamID),
	CONSTRAINT		AwayFK				FOREIGN KEY (AwayID)		REFERENCES Teams(TeamID)
);
CREATE TABLE Innings (
	GameID			INT,
	BattingTeamID	INT,
	InningNumber	INT,
	FallOfWickets	TEXT,
	Score			TEXT,
	CONSTRAINT		InningsPK			PRIMARY KEY (GameID, BattingTeamID, InningNumber),
	CONSTRAINT		InningsGameFK		FOREIGN KEY (GameID)		REFERENCES Games(GameID),
	CONSTRAINT		InningsTeamFK		FOREIGN KEY (BattingTeamID)	REFERENCES Teams(TeamID)
);

DROP TABLE Innings;
DROP TABLE Games;
DROP TABLE Players;
DROP TABLE Teams;
CREATE TABLE Teams (TeamID INTEGER PRIMARY KEY AUTOINCREMENT, TeamName TEXT NOT NULL);
CREATE TABLE Players (TeamID INT, PlayerName TEXT, CONSTRAINT PlayersPK PRIMARY KEY (TeamID, PlayerName), CONSTRAINT PlayersFK FOREIGN KEY (TeamID) REFERENCES Teams(TeamID));
CREATE TABLE Games (GameID INTEGER PRIMARY KEY AUTOINCREMENT, HomeID INT, AwayID INT, GameDate DATE NOT NULL, TossResult TEXT NOT NULL, Decision TEXT NOT NULL, MatchType TEXT NOT NULL, OversOrDays INT NOT NULL, UmpireOne TEXT NOT NULL, UmpireTwo TEXT NOT NULL, CONSTRAINT HomeFK FOREIGN KEY (HomeID) REFERENCES Teams(TeamID), CONSTRAINT AwayFK FOREIGN KEY (AwayID) REFERENCES Teams(TeamID));
CREATE TABLE Innings (GameID INT, BattingTeamID INT, InningNumber INT, FallOfWickets TEXT, Score TEXT, CONSTRAINT InningsPK PRIMARY KEY (GameID, BattingTeamID, InningNumber), CONSTRAINT InningsGameFK FOREIGN KEY (GameID) REFERENCES Games(GameID), CONSTRAINT InningsTeamFK FOREIGN KEY (BattingTeamID) REFERENCES Teams(TeamID));


